window.data = {
  coffee: 0,
  totalCPS: 0,
  producers: [
    {
      id: 'chemex',
      price: 10,
      unlocked: false,
      upgrade: 'Cleaner coffee machine',
      upgradePrice: 100,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 1,
      qty: 0,
    },
    {
      id: 'french_press',
      price: 50,
      unlocked: false,
      upgrade: 'Increased machine pressure',
      upgradePrice: 500,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 2,
      qty: 0,
    },
    {
      id: 'mr._coffee',
      price: 100,
      unlocked: false,
      upgrade: 'Use fresh mountain water',
      upgradePrice: 1000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 5,
      qty: 0,
    },
    {
      id: 'ten_cup_urn',
      price: 500,
      unlocked: false,
      upgrade: 'Upgraded coffee bean grinder',
      upgradePrice: 5000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 10,
      qty: 0,
    },
    {
      id: 'espresso_machine',
      price: 1000,
      unlocked: false,
      upgrade: 'Grind beans to order',
      upgradePrice: 10000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 20,
      qty: 0,
    },
    {
      id: 'ten_gallon_urn',
      price: 5000,
      unlocked: false,
      upgrade: 'Coffee made to order',
      upgradePrice: 50000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 50,
      qty: 0,
    },
    {
      id: 'coffeeshop',
      price: 10000,
      unlocked: false,
      upgrade: 'Extra shot of espresso',
      upgradePrice: 100000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 75,
      qty: 0,
    },
    {
      id: 'coffee_factory',
      price: 50000,
      unlocked: false,
      upgrade: 'Use freshest beans in existence',
      upgradePrice: 500000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 100,
      qty: 0,
    },
    {
      id: 'coffee_fountain',
      price: 100000,
      unlocked: false,
      upgrade: 'Genetically modified coffee beans',
      upgradePrice: 1000000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 200,
      qty: 0,
    },
    {
      id: 'coffee_river',
      price: 500000,
      unlocked: false,
      upgrade: 'Genetically modified water',
      upgradePrice: 5000000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 500,
      qty: 0,
    },
    {
      id: 'coffee_ocean',
      price: 1000000,
      unlocked: false,
      upgrade: 'Cat included with every purchase',
      upgradePrice: 10000000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 1000,
      qty: 0,
    },
    {
      id: 'coffee_planet',
      price: 5000000,
      unlocked: false,
      upgrade: 'Genetically modify everything about our coffee',
      upgradePrice: 50000000,
      upgradeUnlock: false,
      upgradeQty: 0,
      cps: 2000,
      qty: 0,
    },
  ],
};
